---
apiVersion: rhdh.redhat.com/v1alpha6
kind: Backstage
metadata:
  name: lightspeed-test
spec:
  # TODO: should be enabled by default (default-config/flavours/lightspeed/metadata.yaml -> enabledByDefault: true
  flavours:
    - name: lightspeed
      enabled: true
#  application:
#    extraEnvs:
#      secrets:
#        - name: llama-stack-secrets
#          containers:
#            - llama-stack
        #- name: lightspeed-secrets
            #- lightspeed-core

